In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.spatial import ConvexHull

In [2]:
connec = np.array([
    [1,1,0,1,1,0,0,0],
    [1,1,1,0,0,1,0,0],
    [0,1,1,1,0,0,1,0],
    [1,0,1,1,0,0,0,1],
    [1,0,0,0,1,1,0,1],
    [0,1,0,0,1,1,1,0],
    [0,0,1,0,0,1,1,1],
    [0,0,0,1,1,0,1,1],
],dtype=bool)

coords = np.array([
  [-.5,  .5,  .5],
  [-.5,  .5, -.5],
  [ .5,  .5, -.5],
  [ .5,  .5,  .5],
  [-.5, -.5,  .5],
  [-.5, -.5, -.5],
  [ .5, -.5, -.5],
  [ .5, -.5,  .5],
  ], dtype=float)




In [6]:
bits= np.array([0,1,0,0,1,1,1,0],dtype=bool).reshape((1,8))

answer = bits * (bits * connec).T
# answer = np.col((bits * connec).T, [2,4,7]).nodup()

answer = np.array(answer,dtype=int)
# print(answer)

groups = dict([(elem.argmax() ,elem) for elem in answer if elem.any() ])
print(groups)


{1: array([0, 1, 0, 0, 1, 1, 1, 0]), 4: array([0, 0, 0, 0, 1, 1, 0, 0]), 5: array([0, 0, 0, 0, 0, 1, 1, 0])}


In [7]:
for group in groups:
    bit_connec = (1 - bits) * (groups[group] * connec).T
    mid_indices = bit_connec.nonzero()
    print(mid_indices)
    mid_pos = np.array(list(zip(coords[mid_indices[0]], coords[mid_indices[1]])))
    mid_pos = np.mean(mid_pos,axis=1)
    print(mid_pos)
    if len(mid_pos) > 3:
        hull = ConvexHull(mid_pos)

        fig = plt.figure()
        ax = fig.add_subplot(111, projection="3d")
        ax.plot(mid_pos.T[0], mid_pos.T[1], mid_pos.T[2], "ko")

        for s in hull.simplices:
            s = np.append(s, s[0])  # Here we cycle back to the first coordinate
            ax.plot(mid_pos[s, 0], mid_pos[s, 1], mid_pos[s, 2], "r-")

        for i in ["x", "y", "z"]:
            eval("ax.set_{:s}label('{:s}')".format(i, i))

        plt.show()




(array([1, 1, 4, 4, 6, 6], dtype=int64), array([0, 2, 0, 7, 2, 7], dtype=int64))
[[-0.5  0.5  0. ]
 [ 0.   0.5 -0.5]
 [-0.5  0.   0.5]
 [ 0.  -0.5  0.5]
 [ 0.5  0.  -0.5]
 [ 0.5 -0.5  0. ]]


QhullError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)

While executing:  | qhull i Qt
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 457492622  incidence  Qtriangulate  _pre-merge  _zero-centrum
  _max-width  1  Error-roundoff 6.9e-16  _one-merge 4.9e-15
  _near-inside 2.4e-14  Visible-distance 1.4e-15  U-max-coplanar 1.4e-15
  Width-outside 2.8e-15  _wide-facet 8.3e-15  _maxoutside 5.5e-15

The input to qhull appears to be less than 3 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p1(v4):     0   0.5  -0.5
- p3(v3):     0  -0.5   0.5
- p4(v2):   0.5     0  -0.5
- p0(v1):  -0.5   0.5     0

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 6.9e-16.  The center point, facets and distances
to the center point are as follows:

center point        0    0.125   -0.125

facet p3 p4 p0 distance=    0
facet p1 p4 p0 distance=    0
facet p1 p3 p0 distance=    0
facet p1 p3 p4 distance=    0

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:      -0.5       0.5  difference=    1
  1:      -0.5       0.5  difference=    1
  2:      -0.5       0.5  difference=    1

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 6.9e-16.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.
